trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
  tags:    
    include:
    - '*'
  
pr:
  - master
  - develop
  
variables:
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: sdk
  displayName: 'Tool installation'

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.5.1'
  displayName: 'Install Git Version'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
  displayName: 'Restore'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
    additionalArguments: '/output buildserver /nofetch'
  displayName: 'Run Git Version'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'
  displayName: 'Build'

- task: DotNetCoreCLI@2
  displayName: "Install dotnet format"
  inputs:
    command: custom
    custom: tool
    arguments: install -g dotnet-format --version 4.0.130203 --ignore-failed-sources

- task: DotNetCoreCLI@2
  displayName: "Check code format"
  inputs:
    command: 'custom'
    custom: 'format'
    arguments: '--check'

- task: DotNetCoreCLI@2
  displayName: 'Publishing the application'
  condition: or(in(variables['Build.SourceBranch'], 'refs/heads/develop', 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'refs/tags/v'))
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1  
  displayName: 'Publishing the artifacts'
  condition: or(in(variables['Build.SourceBranch'], 'refs/heads/develop', 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'refs/tags/v'))
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'personal-money'
