trigger:
  branches:
    include:
    - master
    - develop
  tags:    
    include:
    - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: personalmoney/api/app

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.5.1'
  displayName: 'Install Git Version'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
    additionalArguments: '/output buildserver /nofetch'
  displayName: 'Run Git Version'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo ##vso[build.updatebuildnumber] $(GitVersion.AssemblySemVer)'
    ignoreLASTEXITCODE: true
    pwsh: true
  displayName: Build Number update
- task: Docker@2
  inputs:
    containerRegistry: 'Github-docker'
    command: 'login'

- task: Docker@2
  displayName: 'Build and push the image'
  condition: in(variables['Build.SourceBranch'], 'refs/heads/develop', 'refs/heads/master')
  inputs:
    containerRegistry: 'Github-docker'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: './.docker/Dockerfile'
    buildContext: '.'
    tags: '$(Build.SourceBranchName)-$(GitVersion.AssemblySemVer)'

- task: Docker@2
  displayName: 'Build and push the image'
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    containerRegistry: 'Github-docker'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: './.docker/Dockerfile'
    buildContext: '.'
    tags: |
      prod-$(GitVersion.AssemblySemVer)
      latest

- task: PublishPipelineArtifact@1
  displayName: "Publishing the file"
  inputs:
    targetPath: './.docker/Heroku-Dockerfile'
    artifact: 'Dockerfile'
    publishLocation: 'pipeline'