
trigger:
  branches:
    include:
    - master
    - develop
  tags:    
    include:
    - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if in(variables['Build.SourceBranchName'], 'develop', 'master') }}:
    TAG: $(Build.BuildId)
  ${{ if contains(variables['Build.SourceBranch'], 'refs/tags/') }}:
    TAG: latest
  imageName: personalmoney/api/app

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    
- task: Docker@2
  inputs:
    containerRegistry: 'Github-docker'
    command: 'login'

- task: Docker@2
  displayName: 'Build and push the image'
  condition: in(variables['Build.SourceBranch'], 'refs/heads/develop', 'refs/heads/master')
  inputs:
    containerRegistry: 'Github-docker'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: './.docker/Dockerfile'
    buildContext: '.'

- task: Docker@2
  displayName: 'Build and push the image'
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    containerRegistry: 'Github-docker'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: './.docker/Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest

- task: PublishPipelineArtifact@1
  displayName: "Publishing the file"
  inputs:
    targetPath: './.docker/Heroku-Dockerfile'
    artifact: 'Dockerfile'
    publishLocation: 'pipeline'