
trigger:
- master
- develop

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    TAG: $(Build.BuildId)
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    TAG: latest
  imageName: docker.pkg.github.com/personalmoney/api/app:$TAG

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    
- task: Docker@2
  inputs:
    containerRegistry: 'Github-docker'
    command: 'login'

- task: Docker@2
  displayName: 'Building the image'
  inputs:
    containerRegistry: 'Github-docker'
    command: 'build'
    Dockerfile: './.docker/Dockerfile'
    buildContext: '.'
    arguments: '-t $imageName'

- task: Docker@2
  displayName: 'Pushing the image'
  inputs:
    containerRegistry: 'Github-docker'
    repository: '$imageName'
    command: 'push'
    tags: 

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $content = Get-Content -Path '.docker/Heroku-Dockerfile'
      $newContent = $content -replace '${TAG}', $(Build.BuildId)
      $newContent | Set-Content -Path '.docker/Heroku-Dockerfile'

- task: PublishPipelineArtifact@1
  displayName: "Publishing the file"
  inputs:
    targetPath: '$(Pipeline.Workspace)/.docker/Heroku-Dockerfile'
    artifact: 'Dockerfile'
    publishLocation: 'pipeline'