
trigger:
- master
- develop

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    TAG: $(Build.BuildId)
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    TAG: latest
  imageName: personalmoney/api/app

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    
- task: Docker@2
  inputs:
    containerRegistry: 'Github-docker'
    command: 'login'

- task: Docker@2
  displayName: 'Build and push the image'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  inputs:
    containerRegistry: 'Github-docker'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: './.docker/Dockerfile'
    buildContext: '.'

- task: Docker@2
  displayName: 'Build and push the image'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    containerRegistry: 'Github-docker'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: './.docker/Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest

- task: PowerShell@2
  displayName: 'Transform the docker file'
  inputs:
    targetType: 'inline'
    script: |
      $content = Get-Content -Path './.docker/Heroku-Dockerfile'
      $newContent = $content -replace '${TAG}', $(Build.BuildId)
      $newContent | Set-Content -Path './.docker/Heroku-Dockerfile'

- task: PublishPipelineArtifact@1
  displayName: "Publishing the file"
  inputs:
    targetPath: '/.docker/Heroku-Dockerfile'
    artifact: 'Dockerfile'
    publishLocation: 'pipeline'